routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
    '/',
    function () {
        return redirect()->route('login');
    }
);

Auth::routes();
Auth::routes(['verify' => true]);
Route::get('/home', 'HomeController@index')->name('home');

Route::group(
    ['middleware' => ['auth', 'verified'], 'prefix' => 'shop'],
    function () {
        Route::get('/', 'ShopController@shop')->name('shop');
        Route::get('/order/product/{product}', 'OrderController@index')->name('order.index');
        Route::get('/order/process/{product}', 'OrderController@process')->name('order.process');
        Route::get('/order/summary/{order}', 'OrderController@summary')->name('order.summary');
        Route::get('/order/retry/{order}', 'OrderController@retry')->name('order.retry');
        Route::get('/orders', 'OrderController@list')->name('order.list');
        Route::post('/search', 'ShopController@search')->name('product.search');
    }
);

Route::group(
    ['middleware' => 'admin', 'prefix' => 'admin'],
    function () {
        Route::get('/', 'HomeController@index');
        Route::get('/users', 'UserController@index')->name('users.index');
        Route::post('/users', 'UserController@store')->name('users.store');
        Route::get('/users/{user}', 'UserController@show')->name('users.show');
        Route::put('/users/{user}', 'UserController@update')->name('users.update');

        Route::resource('product', 'ProductController');
    }
);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use App\Models\Order;

class Product extends Model
{
    protected $guarded = [];

    public function scopeDescription(Builder $query, string $description): Builder
    {
        if ($description) {
            return $query->where('description', 'LIKE', "%$description%");
        }
    }

    public function scopeStatus(Builder $query, int $status): Builder
    {
        return $query->where('status', '=', $status);
    }

    public function order(): HasOne
    {
        return $this->hasOne(Order::Class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use App\Http\Requests\StoreProductRequest;
use App\Http\Requests\UpdateProductRequest;
use App\Repositories\Product\ProductRepository;

class ProductController extends Controller
{

    protected $productRepositorie;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(ProductRepository $productRepositorie)
    {
        $this->productRepositorie = $productRepositorie;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(): View
    {
        $products = $this->productRepositorie->getAllPaginate(10);
        return view('product.index')->with('products', $products);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create(): View
    {
        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreProductRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreProductRequest $request): RedirectResponse
    {
        $this->productRepositorie->create($request->validated());
        return redirect()->route('product.index')->with('success', __('product.product_successfully_created'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\View\View
     */
    public function edit(Product $product): View
    {
        return view('product.edit')->with('product', $product);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\StoreProductRequest  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateProductRequest $request, Product $product): RedirectResponse
    {
        $this->productRepositorie->update($product, $request->validated());
        return redirect()->route('product.index')->with('success', __('product.product_successfully_edited'));
    }
}

resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">

        @if (count($errors) > 0)
        <div class="col-md-9">
            <div class="alert alert-danger alert-dismissible section-margin-top-50">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{!! $error !!}</li>
                        @endforeach
                    </ul>
                </h4>
            </div>
        </div>
        @endif
        <div class="col-md-9">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{route('home')}}">@lang('global.home')</a></li>
                    <li class="breadcrumb-item"><a href="{{route('product.index')}}">@lang('product.products')</a></li>
                    <li class="breadcrumb-item active" aria-current="page">@lang('global.create')</li>
                </ol>
            </nav>
            <div class="card">
                <div class="card-header">@lang('product.info_product')</div>

                <div class="card-body">

                    <form method="POST" action="{{route('product.store')}}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="formGroupExampleInput">@lang('global.description')</label>
                            <input type="text" class="form-control" name="description" id="description" maxlength="200" required placeholder="@lang('global.description')">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput2">@lang('global.price')</label>
                            <input type="text"  pattern="[0-9]*"  min="0" class="form-control soloNumeros" name="price" id="price"maxlength="11" required placeholder="@lang('global.price')">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput2">@lang('global.status')</label>
                            <select class="form-control" name="status" id="status">
                                <option value="1">@lang('Activo')</option>
                                <option value="0">@lang('Inactivo')</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput2">@lang('global.image')</label>
                            <input type="file" class="form-control-file" name="image" id="image" accept=".jpeg,.jpg,.png" placeholder="@lang('global.image')">
                        </div>
                        <button type="submit" class="btn btn-primary">@lang('global.send')</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">

        @if (count($errors) > 0)
        <div class="col-md-9">
            <div class="alert alert-danger alert-dismissible section-margin-top-50">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{!! $error !!}</li>
                        @endforeach
                    </ul>
                </h4>
            </div>
        </div>
        @endif
        <div class="col-md-9">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{route('home')}}">@lang('global.home')</a></li>
                    <li class="breadcrumb-item"><a href="{{route('product.index')}}">@lang('product.products')</a></li>
                    <li class="breadcrumb-item active" aria-current="page">@lang('global.edit')</li>
                </ol>
            </nav>
            <div class="card">
                <div class="card-header">@lang('product.info_product') </div>

                <div class="card-body">

                    <form method="POST" action="{{route('product.update', $product->id)}}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="formGroupExampleInput">@lang('global.description')</label>
                            <input type="text" class="form-control" name="description" id="description" maxlength="200" required placeholder="@lang('global.description')" value="{{$product->description}}">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput2">@lang('global.price')</label>
                            <input type="text"  pattern="[0-9]*"  min="0" class="form-control soloNumeros" name="price" id="price" maxlength="11" required placeholder="@lang('global.price')" value="{{$product->price}}">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput2">@lang('global.status')</label>
                            <select class="form-control" name="status" id="status">
                                <option value="1" @if($product->status == 1) selected @endif>@lang('Activo')</option>
                                <option value="0" @if($product->status == 0) selected @endif>@lang('Inactivo')</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput2">@lang('global.image')</label>
                            <input type="file" class="form-control-file" name="image" id="image" accept=".jpeg,.jpg,.png" placeholder="@lang('global.image')">
                        </div>
                        <button type="submit" class="btn btn-primary">@lang('global.send')</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{route('home')}}">{{__('global.home')}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{__('product.products')}}</li>
                </ol>
            </nav>

            @if(Session::has('success'))
                 <div class="alert alert-success" role="alert">
                     {{ Session::get('success') }}
                </div>
            @endif

            <div class="card">
                <div class="card-header">@lang('product.list_products')</div>

                <div class="card-body">
                  
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">@lang('global.image')</th>
                            <th scope="col">@lang('global.description')</th>
                            <th scope="col">@lang('global.price')</th>
                            <th scope="col">@lang('global.status')</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach($products as $product)
                            <tr>
                                <td><img src="{{asset('products/'.$product->image)}}" style="max-width:200px;max-height:200px;"/></td>
                                <td>{{$product->description}}</td>
                                <td>{{$product->price}}</td>
                                <td>@if($product->status) <span class="badge badge-success">Activo</span> @else <span class="badge badge-danger">Inactivo</span> @endif</td>
                                <td><a href="{{route('product.edit', $product->id)}}">@lang('global.edit')</a></td>
                            </tr>
                        @endforeach
                      
                    </tbody>
                    </table>

                    {{ $products->links() }}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection